Repository KhNURE-Timetable-Synchronizer/KhNURE-Timetable-Synchronizer, pull requests merged in 2024-06, with the labels that each got.

#58 KTS-69 Create GET endpoint for getting all requests for getting a role of Links Coordinator
  backend/src/main/java/com/khnure/timetable/synchronizer/config/SecurityConfiguration.java
  backend/src/main/java/com/khnure/timetable/synchronizer/controller/RequestLinksCoordinatorTimetableController.java
  backend/src/main/java/com/khnure/timetable/synchronizer/controller/UserController.java
  backend/src/main/java/com/khnure/timetable/synchronizer/dto/PaginationDto.java
  backend/src/main/java/com/khnure/timetable/synchronizer/dto/RequestLinksCoordinatorTimetableGetDto.java
  backend/src/main/java/com/khnure/timetable/synchronizer/dto/RequestLinksCoordinatorTimetablePostDto.java
  backend/src/main/java/com/khnure/timetable/synchronizer/exception/handler/RequestsExceptionHandler.java
  backend/src/main/java/com/khnure/timetable/synchronizer/exception/handler/ValidationExceptionHandler.java
  backend/src/main/java/com/khnure/timetable/synchronizer/mapper/RequestLinksCoordinatorTimetableMapper.java
  backend/src/main/java/com/khnure/timetable/synchronizer/model/RequestLinksCoordinatorTimetable.java
  backend/src/main/java/com/khnure/timetable/synchronizer/repository/RequestLinksCoordinatorTimetableRepository.java
  backend/src/main/java/com/khnure/timetable/synchronizer/repository/UserRepository.java
  backend/src/main/java/com/khnure/timetable/synchronizer/service/RequestLinksCoordinatorTimetableService.java
  backend/src/main/java/com/khnure/timetable/synchronizer/service/UserService.java
  backend/src/main/java/com/khnure/timetable/synchronizer/validator/RequestLinksCoordinatorTimetableGroup.java
  backend/src/main/java/com/khnure/timetable/synchronizer/validator/UserGroup.java
Labels: enhancement

#61 KTS-83 Fix the logic for adding requests to the role Links Coordinator
  backend/src/main/java/com/khnure/timetable/synchronizer/repository/RequestLinksCoordinatorTimetableRepository.java
  backend/src/main/java/com/khnure/timetable/synchronizer/service/RequestLinksCoordinatorTimetableService.java
Labels: bug

#62 KTS-93 Create GET endpoint for getting selected request for getting a…
  backend/src/main/java/com/khnure/timetable/synchronizer/config/SecurityConfiguration.java
  backend/src/main/java/com/khnure/timetable/synchronizer/controller/RequestLinksCoordinatorTimetableController.java
  backend/src/main/java/com/khnure/timetable/synchronizer/repository/RequestLinksCoordinatorTimetableRepository.java
  backend/src/main/java/com/khnure/timetable/synchronizer/service/RequestLinksCoordinatorTimetableService.java
Labels: enhancement

#63 KTS-92 Refactor pagination usage
  backend/src/main/java/com/khnure/timetable/synchronizer/controller/RequestLinksCoordinatorTimetableController.java
  backend/src/main/java/com/khnure/timetable/synchronizer/controller/UserController.java
  backend/src/main/java/com/khnure/timetable/synchronizer/dto/PaginationResponse.java
Labels: refactoring

#65 KTS-93 Security fix
  backend/src/main/java/com/khnure/timetable/synchronizer/config/SecurityConfiguration.java
Labels: bug

#66 KTS-69 Security fix
  backend/src/main/java/com/khnure/timetable/synchronizer/config/SecurityConfiguration.java
Labels: bug
